import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:over_money_manager/domain/logic/auth/auth_bloc.dart';
import 'package:over_money_manager/generated/l10n.dart';
import 'package:over_money_manager/resources/resources.dart';
import 'package:over_money_manager/ui/router/app_hero_tags.dart';
import 'package:over_money_manager/ui/widgets/auth_form/auth_form_pakages.dart';
import 'package:over_money_manager/ui/widgets/custom_appbar/custom_appbar.dart';
import 'package:over_money_manager/ui/widgets/limit_container/limit_container.dart';
// ===========================================================================
part 'auth_page.dart';
part 'auth_page_content.dart';
