// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsp0-iHpqYFj4q-lYvmqTNu8AXAENjkEs',
    appId: '1:258563425752:web:581a57749379c6db841ead',
    messagingSenderId: '258563425752',
    projectId: 'over-money-manager',
    authDomain: 'over-money-manager.firebaseapp.com',
    storageBucket: 'over-money-manager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6jLyLqe836U26JNuZ1rKNcihmHr0z7wY',
    appId: '1:258563425752:android:451744bcaef37daa841ead',
    messagingSenderId: '258563425752',
    projectId: 'over-money-manager',
    storageBucket: 'over-money-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ31ngnjgj0FRpu94kGnkJr-Rkq6q1ETI',
    appId: '1:258563425752:ios:78f4b2b0a71d23ec841ead',
    messagingSenderId: '258563425752',
    projectId: 'over-money-manager',
    storageBucket: 'over-money-manager.appspot.com',
    iosClientId: '258563425752-0lkcmck38orh43q4dk26c8qauuou6574.apps.googleusercontent.com',
    iosBundleId: 'com.example.overMoneyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ31ngnjgj0FRpu94kGnkJr-Rkq6q1ETI',
    appId: '1:258563425752:ios:78f4b2b0a71d23ec841ead',
    messagingSenderId: '258563425752',
    projectId: 'over-money-manager',
    storageBucket: 'over-money-manager.appspot.com',
    iosClientId: '258563425752-0lkcmck38orh43q4dk26c8qauuou6574.apps.googleusercontent.com',
    iosBundleId: 'com.example.overMoneyManager',
  );
}
